### ISSUE TITLE
Underscores disappear when cursor travels past line containing them

### ISSUE THREAD

**Issue by dullroar** [linuxmint/xed#39]
This is a weird one, will see if I can explain it. I can't capture a screenshot of it, but I can reliably reproduce it.

**Environment**
- Linux Mint 18 Sarah with Cinnamon
- 4.4.0-21 Linux kernel
- Lenovo Yoga 2 Pro
- Integrated Intel graphics adapter
- HiDPI display (3200x1800) with User interface scaling set to Auto
- xed 1.0.6

**Problem**

Opened a C source file (tagreader_c.c from TagLib's example programs). There are lines like:

``` c
TagLib_File *file;
TagLib_Tag *tag;
```

When I cursor past them going "down," they appear to change to (render as):

``` c
TagLib File *file;
TagLib Tag *tag;
```

When I cursor back "up" past them, the underscores reappear. It is **_very**_ reproducible. Yet when I take a screenshot of the window with the underscores missing, they show up in the screenshot.

Strange, yes?

**Comment by dullroar** [comment]
Minor addition: Playing around with it, I notice the same behavior not just on the cursor traveling down directly via the down arrow key, but also if the cursor is on one of the lines with underscores, and I travel to the right with the right arrow key until it "wraps" down to the next line. When the cursor hits the start of the next line the underscores in the line it just left are still there, but when it then travels one more character to the right on the newly-arrived line, the underscores on the line above it disappear. Thought it could be another clue.

**Comment by JosephMcc** [comment]
I just tested this on the latest git master and couldn't reproduce it. I tried it under both normal and HiDpi without issue. Have you by chance changed to another font? It's quite possible this was fixed with all the changes to Xed's internals. I'll leave it open for now until you get the chance to test under a newer version.

**Comment by dullroar** [comment]
I upgraded Linux Mint to 18.1, which took xed to 1.2.2, and I am still seeing the behavior, although it is slightly modified. Now the underlines don't disappear when the cursor is on the line with them, but on a line or two afterwards, if using the arrow keys to move the cursor down. Then further down the file they will reappear.

There is something about the behavior that almost makes me wonder if it is related to syntax highlighting. the symptoms appear in C and C# source files, for example, but not in bash scripts.

**Comment by ziggurats** [comment]
I had the same issue.  Only seems to happen with the default system font and size (monospace 10).  Any other font, any other size, it's OK.  At that size, the underscores appear to lose half their height after the active line moves past them.
Tried with different themes and in a new file (so no syntax highlighting), and in each case when using monospace 10 the underscores disappear.
Mint 18.1 Cinnamon, Kernel 4.8.0-42, Intel Integrated Graphic/Nvidia GM107M, nouveau driver 1:1.0.12-1build2

**Comment by dullroar** [comment]
@ziggurats Confirmed same behavior on mine, except on mine the default is monospace 9. I changed it to monospace 10 and the issue went away. Weird. Mint 18.1 Cinnamon, Kernel 4.4.0-66, Intel Haswell-ULT Integrated Graphics controller, intel driver.

**Comment by JosephMcc** [comment]
If I supply the 64-bit debs built from git master, would you guys be willing to install and test them? I can't replicate the issue but xed has seen major work since the version released in Mint 18.1.

**Comment by ziggurats** [comment]
@JosephMcc sure, I can do that.

**Comment by JosephMcc** [comment]
You can get them here: https://www.dropbox.com/s/1jphng4cwcjj4np/xed-debs.zip?dl=0

**Comment by ziggurats** [comment]
@JosephMcc I removed the existing packages, installed the 1.2.2 and common_1.2.2 you provided, and I'm still seeing the same issue.  To add a little more detail, as I type underscores they aren't visible.  When I hit enter to go to the next line, the underscores appear. When I hit enter again, they disappear.  After that, or if I open a file, when the cursor is above, on the same line as, or on the line immediately below the line that contains the underscores, the character is visible.  Anywhere below that, and they disappear.  If I use the mouse wheel to scroll further down the file then scroll back up the underscores reappear.  Using the arrow keys to go back up, the underscores disappear when the cursor is on the line below, and reappear when on the same line as them.
FYI, I'm working on a 4k display - 3840x2160 - which mught explain the difference in the system default font between myself and dullroar

**Comment by dullroar** [comment]
@ziggurats description of the behavior mirrors my experience, too.

**Comment by JosephMcc** [comment]
@dullroar Are you running on a HiDPI display as well?

**Comment by dullroar** [comment]
Yes. HiDPI display (3200x1800) with User interface scaling set to Auto.

**Comment by JosephMcc** [comment]
Well that would likely explain my lack of ability to reproduce it :)

**Comment by JosephMcc** [comment]
I now have a HiDPI display for testing. I was trying to reproduce this under Xed 1.4.6 with various font sizes and still cannot seem to reproduce it.

**Comment by P-Shreyas** [comment]
@dullroar  I am also facing the same issue. I am running xed version 1.4.4 on Linux Mint 18.2. To add a little more detail,

1. Underscores do not appear as you type them.
2. Visible underscores are not erased with Backspace key.(the cursor moves over it and the underscore stays there)
3. Hidden underscores reappear after saving the file with the keyboard shortcut.(indepndent of cursor position)
4. 1 and 2 do not occur if you have a "\ (double quote and slash) on the same line with underscores.

**Comment by geckolinux** [comment]
I´m seeing this bug as described in #184 (sorry for the dupe). I would like to add that I have a high resolution display (not sure if it's technically HiDPI or not), and I have my interface scaled by a factor of 1.2.

**Comment by dullroar** [comment]
I am no longer seeing this, as of:

- xed 1.4.6
- Linux Mint 18.2 Sonya with Cinnamon
- Linux kernel 4.13.0-26

All else (machine, etc.) are the same. Can anyone else in the thread see if they are seeing it? I glanced at the commits between 1.4.4 and 1.4.6 and nothing leaped out at me. Something changed in Mint or Cinnamon? If someone else can confirm, we can close this.

**Comment by geckolinux** [comment]
Unfortunately the bug still exists in xed 1.6.3 with openSUSE Tumbleweed current. I just now opened a document to test. I replaced one of the X's with an underscore like this:
![see](https://user-images.githubusercontent.com/2692138/34927072-8ec25086-f981-11e7-9069-71c5bde4326b.png)

But this is what I saw (edited in Gimp to reflect what I saw. As soon as I took a screenshot the underscore appeared again):
![see](https://user-images.githubusercontent.com/2692138/34927083-98f19d00-f981-11e7-8011-36a2dafabe90.png)

**Comment by geckolinux** [comment]
@ziggurats Interesting, it does indeed have something to do with the font size. I also have configured a non-system font (DejaVu Sans Mono) in 14pt size, which exhibits this bug, but if I change it to 13pt or 15pt this bug goes away.

**Comment by dullroar** [comment]
And I just confirmed that I am set to "Use the system fixed width font (Monospace 10)" under Fonts & Colors in Preferences, but I am no longer seeing the behavior. Weird.

**Comment by ziggurats** [comment]
I don't seem to have DejaVu Sans Mono installed.  The closest I have is DejaVu Sans Mono Bold, and with that font at 10 pt I see the underscores go to half height as I move down below the line, and they're restored as I go back up past them.  I also see the same thing you're seeing with screenshots

**Comment by geckolinux** [comment]
BTW I'm using a DPI scale factor of 1.2 in Cinnamon.

**Comment by dullroar** [comment]
And I am set to Auto, which is equivalent to Double (HiDPI), also in Cinnamon.

**Comment by ziggurats** [comment]
I'm set to Normal, with a text scaling factor of 1.4

**Comment by JosephMcc** [comment]
This seems to be down to certain combinations of fonts and scaling factors. Have any of you tried testing with the exact same settings in Gedit? In the end Xed doesn't handle these things directly. The issue lies either with the fonts or GtkTextView/SourceView and I don't believe are really fixable on our side.
